### ISSUE TITLE
Question about "missing" RPC calls and the chainHead_unstable_call API

### ISSUE THREAD

**Issue by jsdw** [paritytech/json-rpc-interface-spec#14]
Hello!

Is it correct that the results of current RPC methods like `payment_queryFeeDetails` will be accessible instead via `chainHead_unstable_call` in this new API?

I guess I'm wondering; where can I look to see which calls are available via this `chainHead_unstable_call` method (I'm not familiar with the node runtime API stuff; I assume this calls into it)? Are there any RPC methods that would not have any sort of replacement with this new API (I assume not)?

Thanks!

**Comment by tomaka** [comment]
> Is it correct that the results of current RPC methods like payment_queryFeeDetails will be accessible instead via chainHead_unstable_call in this new API?

Yes!
You just do `chainHead_unstable_call(subscriptionId, blockHash, "TransactionPaymentApi_query_info", extrinsic)`

> Are there any RPC methods that would not have any sort of replacement with this new API (I assume not)?

RPC methods that are related to the runtime can all be replaced with `chainHead_unstable_call`.

To answer the question, there are RPC functions that don't have replacements: `babe_epochAuthorship`, `system_addLogFilter`, `offchain_localStorageGet`, etc. Some of them simply can't be implemented by a light client, and none of these are necessary for frontend UIs. They exist only for node operators or devs to debug potential issues. I suspect that many of them exist just for the sake of existing, but if there's actually a need for some of them we can introduce equivalent methods before deprecating the old API.
