### ISSUE TITLE
chainHead: Calls into runtime without the `runtimeUpdates` flag?

### ISSUE THREAD

**Issue by lexnv** [paritytech/json-rpc-interface-spec#30]
In order to execute `chainHead_unstable_call` on a block provided by the `chainHead_unstable_follow` subscription, the user should provide the `runtimeUpdates` flag set true.
If the `runtimeUpgrades` flag is set, then the substrate will provide additional details to help users identify if a runtime update happened.

Users that are not interested in runtime upgrades could perform `chainHead_unstable_call` directly. Upon a breaking change, the user is responsible to fetch and retry with appropriate parameters.

Considering that updates are not that frequent, what would be the impact of allowing users to call into runtime via `chainHead_unstable_call` regardless of whether the `runtimeUpdates` is set or not?

I'd expect this to have some implications on the light client side. Would it be possible for the light client to execute runtime API calls without having the extra information provided by the `runtimeUpdates` flag?

**Comment by bkchr** [comment]
I also don't really get why we can not do `chainHead_unstable_call` without `runtimeUpdates` being set to `true`. I mean I get that it will take slightly more time to do the runtime call as the light client still has to get the runtime to verify the execution proof. However, the call is async and would just take longer to answer to the caller?

Maybe @tomaka can give some more details here :)

**Comment by tomaka** [comment]
> I mean I get that it will take slightly more time to do the runtime call as the light client still has to get the runtime to verify the execution proof.

The entire point of that new API is that everything is explicit. There's no hidden cost to what you're doing.

If you were able to call `chainHead_unstable_call` when `runtimeUpdates` is `true`, and call `chainHead_unstable_call` twice with the same block, then is the light client going to download the runtime twice? That would be quite a waste. Should it keep the runtime in cache? But that's a hidden cost.

The entire design is that `runtimeUpdates == true` instructs the client to manage the runtime and keep the runtimes in its memory.

**Comment by bkchr** [comment]
> The entire design is that `runtimeUpdates == true` instructs the client to manage the runtime and keep the runtimes in its memory.

Sounds reasonable, but why not then make this more clear? By reading the docs this wasn't that clear to me. I would probably call it something like `efficientRuntimeCalls` or something better indicating the purpose behind this. Tracking if a runtime upgrade has happened can be done using the digest by the light client and thus, we could always report to the user if there happened a runtime upgrade. If the user then wants to know the runtime version, they can do the runtime call on their own. I don't see the requirement to have always the runtime version being supplied on a runtime upgrade. The `chainHead_unstable_call` could also get some optional parameter `hint_cache_runtime` for the node. The node would be free to ignore this hint or too keep the runtime only in cache for some time. These costs of potentially downloading every time and memory usage can be documented. There are maybe applications which are constantly listening to block imports, but only need to execute some runtime call on certain actions or whatever. Thus, they would not really require that the runtime is always kept in memory. But maybe this hint isn't worth all the code to be written for this edge case feature. IDK.

**Comment by tomaka** [comment]
> I don't see the requirement to have always the runtime version being supplied on a runtime upgrade.

What's the point of knowing that a runtime upgrade happened without any other information?

> There are maybe applications which are constantly listening to block imports, but only need to execute some runtime call on certain actions or whatever.

How would the application know which runtime calls are available without having accessed the runtime information beforehand?

> could also get some optional parameter hint_cache_runtime for the node

> These costs of **potentially**

This is very precisely the exact precise thing that I want to not have.

The design is:
- `runtimeUpdates == false` means you only care about blocks. You don't care about the runtime, you're not going to need the metadata, you're not going to do calls, etc.
- `runtimeUpdates == true` means you need all of these things, and as such you get access to more features.

I don't see any advantage in what you're suggesting and I don't see which problem you're trying to solve.
If the problem is that the flag is misnamed, then let's go forward and rename it.

**Comment by bkchr** [comment]
Yeah good points! I mean I wasn't sure about my idea, after writing it down :D 



> If the problem is that the flag is misnamed, then let's go forward and rename it.

:+1:
