### ISSUE TITLE
Are all the fields of the runtime spec necessary?

### ISSUE THREAD

**Issue by tomaka** [paritytech/json-rpc-interface-spec#40]
This concern the `spec` field found here: https://paritytech.github.io/json-rpc-interface-spec/api/chainHead_unstable_follow.html#valid

Right now it matches the "runtime version" exposed by the runtime, except that it is missing the `state_version` field.

I was thinking of adding this `state_version`. However, the value of this field is completely useless for JSON-RPC clients. It's an information that the node uses to determine the encoding of the trie.

Rather than add `state_version`, I'm wondering if it doesn't make more sense to leave aside fields that aren't necessary.

We need to leave `transactionVersion` and `specVersion` because they're used to encode transactions. We should maybe also leave `specName`, `implName` and `implVersion` for debugging purposes. `apis` is important to know which entry points are available.

That leaves `authoringVersion` that is useless and could be removed.

**Comment by tomaka** [comment]
Basically the question in play here is: do we simply return the exact same definition as the one in the runtime, or do we only return what is important for a JSON-RPC client to know?

I would vote for the latter.

**Comment by jsdw** [comment]
I guess there's a mix of data useful for debugging, data necessary for using the API, and data that's presumably not useful for either of those, so I'd be happy not having the latter also!

(I suppose if the node returned extra properties on top of what is specified, it's still comforming to the spec? So the spec can be intentionally more precise and the implementation can decide to return extra bits for debugging or whatever?)

**Comment by tomaka** [comment]
> I suppose if the node returned extra properties on top of what is specified, it's still comforming to the spec?

No, because what tends to happen if you do that is that client developers notice that the extra fields are there and start relying on them.

**Comment by jsdw** [comment]
I was going to debate this perspective, because it had occurred to me already, but I do also like the idea that the spec if precise in this way.

Would it affect backward compatibility too? Ie could we add more properties to some result in the spec and still say that nodes returning this additional property conform to the older spec version too? Or would you see any such changes as requiring a new method name/version to be added each time?

**Comment by tomaka** [comment]
If we add more properties then we should change the version.

If we were to add fields that are only returned by some nodes and not others, then:

- Either the client can work anyway even if the fields are missing, in which case the question is why do you need these fields in the first place?
- Or the client can't function properly if these fields are missing. But determining whether a client is compatible with a server is what the version number is for.
