### ISSUE TITLE
`chainHead_storage`: Extend reported error events

### ISSUE THREAD

**Issue by lexnv** [paritytech/json-rpc-interface-spec#63]
The [chainHead_storage](https://github.com/paritytech/json-rpc-interface-spec/blob/main/src/api/chainHead_unstable_storage.md) spec mentioned the following about errors:

```bash
{
    "event": "error",
    "error": "..."
}
```

> error is a human-readable error message indicating why the call has failed. This string isn't meant to be shown to end users, but is for developers to understand the problem.
This can only be the first event generated by this subscription. No other event will be generated with this subscription.

Considering that we may have multiple items to query, I do wonder:
- Could we generate the error event after providing items responses?
  We might receive a query [Value::A, Value::B, Hash::C]. Processing the items we would produce in the following order:
    - `event = items with value::A`: provides the storage value for A
    - `event = error key=0x.. type=Value`: failed to fetch from storage for some reason (ie OOM, bad disk sector)
    - `event = items with hash::C` : provides the storage hash for C
    - `event = done`: this transforms the events a bit a makes the error event non-terminal since we could and may process other items

- We would need a way to identity which error is coming from which item in the provided query. We could currently encode the `query::key` and `query::type` into the error string but that might be a bit unfriendly. Would an error of the following shape provide more useful info?

```bash
{ "event": "error", "key": "0x..", "type": Hash, "error": "String with reason" }
```

Such we could disambiguate between multiple query types made with the same query key, and would allow the server to process items out of line in arbitrary order.

The same would apply for `inaccessible` as well
> The inaccessible event indicates that the storage value has failed to be retrieved from the network.
No more event will be generated with this subscription.

// cc: @tomaka @josepot @jsdw @paritytech/subxt-team 

Related to: https://github.com/paritytech/substrate/pull/14551

**Comment by tomaka** [comment]
The only error that smoldot can produce here happens if smoldot can't decode the header of the block, which can only happen if the chain is a parachain.

I'm not sure what error you want to return from a full node?

**Comment by lexnv** [comment]
The substrate APIs return this [Error](https://github.com/paritytech/substrate/blob/2447feacba058d14a878d0f6d921cc4de7f018ff/primitives/blockchain/src/error.rs#L49), which has a `String` type for the storage error (`Storage(String),`).

The `StorageProvider` implementations would first fetch the `State` of the block [here](https://github.com/paritytech/substrate/blob/2447feacba058d14a878d0f6d921cc4de7f018ff/client/service/src/client/client.rs#L1485-L1487), which might also fail [when](https://github.com/paritytech/substrate/blob/2447feacba058d14a878d0f6d921cc4de7f018ff/client/db/src/lib.rs#L2392): 
 - the header is not present in the metadata, or in invalid format
 - pinning the block in memory failed (most probably the state has been discarded)
 
Then the storage call might fail with some error returned from the `trie-db`.

Some errors might also originate from reading bad blocks from disk; or even from some bugs in the logic of substrate itself.

We would, in this case, return the stringified error that substrate hands us back in the higher-level APIs of the client

**Comment by josepot** [comment]
> The substrate APIs return this [Error](https://github.com/paritytech/substrate/blob/2447feacba058d14a878d0f6d921cc4de7f018ff/primitives/blockchain/src/error.rs#L49), which has a `String` type for the storage error (`Storage(String),`).
> 
> The `StorageProvider` implementations would first fetch the `State` of the block [here](https://github.com/paritytech/substrate/blob/2447feacba058d14a878d0f6d921cc4de7f018ff/client/service/src/client/client.rs#L1485-L1487), which might also fail [when](https://github.com/paritytech/substrate/blob/2447feacba058d14a878d0f6d921cc4de7f018ff/client/db/src/lib.rs#L2392):
> 
> * the header is not present in the metadata, or in invalid format
> * pinning the block in memory failed (most probably the state has been discarded)
> 
> Then the storage call might fail with some error returned from the `trie-db`.
> 
> Some errors might also originate from reading bad blocks from disk; or even from some bugs in the logic of substrate itself.
> 
> We would, in this case, return the stringified error that substrate hands us back in the higher-level APIs of the client

If I understand correctly (and I may have overlooked something), the errors you're discussing aren't tied to specific `key`s queried but are instead related to the block as a whole. Therefore, it may not be necessary to have such granular error reporting. 

I was under the impression that, at the `key` level, the worst-case scenarios would be a malformed `key` or a `key` that doesn't yield a value. In these instances, the server would simply respond with `null`. So, if my understanding is correct, there might not be a need for such detailed errors.

**Comment by tomaka** [comment]
> The StorageProvider implementations would first fetch the State of the block [here](https://github.com/paritytech/substrate/blob/2447feacba058d14a878d0f6d921cc4de7f018ff/client/service/src/client/client.rs#L1485-L1487), which might also fail [when](https://github.com/paritytech/substrate/blob/2447feacba058d14a878d0f6d921cc4de7f018ff/client/db/src/lib.rs#L2392):
>
>    the header is not present in the metadata, or in invalid format
>    pinning the block in memory failed (most probably the state has been discarded)

This is the reason why `chainHead_follow` pins blocks. When a block is pinned, the JSON-RPC client is guaranteed that its storage is accessible. The two reasons that you give would thus be bugs in Substrate.

> or even from some bugs in the logic of substrate itself.

When writing a spec, you're assuming that bugs don't exist. You can't handle situations where bugs are present. To give an absurd example, I'm not going to add a `maybeValueIsNotExact` boolean just in case Substrate has a bug that causes it to return corrupt values. That's just not something that the JSON-RPC client is supposed to deal with.

If there's a bug, the only appropriate course of action IMO is either panic (but I know that Parity doesn't accept that, for some reason) or for the JSON-RPC server to entirely shut down. Disconnecting the client can also work, but isn't great.

> Some errors might also originate from reading bad blocks from disk; 

That's a good reason to return an error. However, I would suggest to detect that before sending back the result, and return the `error` notification first thing first.

While it's convenient for you, the server, to be able to return an error at any point, the problem is: what is the JSON-RPC client supposed to do?
If an `error` notification is returned at any point, rather than just at the start, it means that the client can't immediately process the values that it receives, and instead has to buffer them up just in case an `error` is returned and it has to throw everything away. That's not great.

> I was under the impression that, at the key level, the worst-case scenarios would be a malformed key or a key that doesn't yield a value. In these instances, the server would simply respond with null

The server must not return `null` if the key is malformed. It must respond with a JSON-RPC error, as explained in the text.

**Comment by lexnv** [comment]
That makes total sense, thanks for the explanations here 🙏 

> If I understand correctly (and I may have overlooked something), the errors you're discussing aren't tied to specific keys queried but are instead related to the block as a whole. Therefore, it may not be necessary to have such granular error reporting.

I believe each key query would call into the trie-db crate which might fail at the key level. But I don't have the whole context on how substrate would handle those scenarios indeed.

> and instead has to buffer them up just in case an error is returned and it has to throw everything away. That's not great.

Would the returned queries change over time for the same block? Could the user make another RPC call with a subset of the first query for which the things failed initially? 🤔 

We could also buffer things up in substrate and only return the items as the last event.

Just to make sure I understood the spec correctly, I'm also thinking of the following scenario to get the implementation right in Substrate:
- the user provides say 100 keys for different queries
- say substrate for whatever reason would only be able to process 5 at a time
- we'd process the first 5 keys and only if they are all successful we'd return the item event
- then we'd generate the wait-for-continue event and expect `chainHead_storage_continue` method to be called
- now for the next 5 keys substrate processes, say the query for the key 4 fails for one of the reasons above, which might be recoverable at the next call
  - for example: OOM killed another process and we'd have more memory available
  - linux might reallocate/recover the bad disk sectors and in doing so we could process it 

Wouldn't it be beneficial for the user and the JSON-RPC server to provide the result of the first 5 keys + the next 3 keys, such that the next query for the node would include only a subset of the first (ie 92 keys vs 100 keys)?
Otherwise, substrate would need to process again the first 8 queries for which there's already a result. Scaling things up the worst case here would be N - 1 successful queries, then 1 failure.

Another aspect is that it might not be practical to hold a large number of responses in the memory of the node.

Users might be able to make some progress and do some other processing while waiting for the complete response to arrive.

I was thinking of the `chainHead_storage` items parameter to allow us to handle multiple calls. Users could batch the requests and the server would provide a response for each request. And only as a transport optimization to allow multiple responses into the same notification. 

I'm just asking these to make sure we'd get the implementation right into substate :D

**Comment by tomaka** [comment]
> Could the user make another RPC call with a subset of the first query for which the things failed initially? thinking

> Wouldn't it be beneficial for the user and the JSON-RPC server to provide the result of the first 5 keys + the next 3 keys, such that the next query for the node would include only a subset of the first (ie 92 keys vs 100 keys)?

I don't think the JSON-RPC client needs to know that. We're very much in "this is never supposed to happen" territory.
If a full node has some kind of disk corruption, I prefer the approach of telling the user "hey, there's something wrong with the node that you're connected to" rather than showing a partially-working UI where some items are missing for an incomprehensible reason.

> now for the next 5 keys substrate processes, say the query for the key 4 fails for one of the reasons above, which might be recoverable at the next call

Another thing to highlight is that there's also an `inaccessible` event, that can be returned at any point.
The difference between `error` and `inaccessible` is that `inaccessible` is potentially recoverable while `error` is not. If `error` is returned, that means that there's no point in repeating the same call, as it will result in the same error.
If an error is potentially recoverable, then you should generate `inaccessible` rather than `error`.

I'm trying to think about how JSON-RPC client-side libraries handle `error` and `inaccessible`, and if there's a problem with producing an `error` as the non-first result, but I have trouble wrapping my head around this.

**Comment by lexnv** [comment]
That makes perfect sense!

-  https://github.com/paritytech/json-rpc-interface-spec/pull/66  This would allow substrate to say: "Hey I'm processing only the first 5 items, I'm discharging the rest"

I do wonder in this case, the [waiting-for-continue](https://github.com/paritytech/json-rpc-interface-spec/blob/main/src/api/chainHead_unstable_storage.md#waiting-for-continue) mentions:

> The waiting-for-continue event is generated after at least one "item" event has been generated, and indicates that the JSON-RPC client must call chainHead_unstable_storageContinue before more events are generated.

This means that we cannot generate the event without providing some items as a result first.
We'd have to iterate over keys, then for each key fetch the storage value or hash.

Since we may not know in advance if the paginated query could fail, because we don't produce all the descendent keys to properly check if the storage access might fail, would it make sense in this scenario to have the `error` event returned after producing some items?
