### ISSUE TITLE
chainHead_follow: Naming convention of the generated events

### ISSUE THREAD

**Issue by lexnv** [paritytech/json-rpc-interface-spec#74]
While implementing the events serialization / deserialization I've noticed the following:
- events prior to limits PR had `camelCase` naming convention:

```bash
"event": "bestBlockChanged",
"event": "newBlock",
```
- newly added events that offer responses to the other methods are `kebab-case`:

```bash
"event": "operation-body-done",
"event": "operation-call-done",
"event": "operation-storage-items",
"event": "operation-storage-done",
...
```

From the substrate implementation point of view, and maybe from the user's perspective, it would be simpler/clearer to have a uniform convention for the naming of events?
Would like to hear your thoughts on this 🙏 

// cc @tomaka @josepot @paritytech/subxt-team

**Comment by tomaka** [comment]
Yeah that's not intended. Everything is supposed to be `camelCase`, because almost all JSON documents are `camelCase`.
