### ISSUE TITLE
`chainHead_follow`: Does a `Finalized` event guarantee that all `NewBlocks` seen before it are either finalized or pruned?

### ISSUE THREAD

**Issue by jsdw** [paritytech/json-rpc-interface-spec#97]
`chainHead_follow` will generate `NewBlock` and `BestBlock` events as blocks are seen. Eventually it generates a `Finalized` event with a list of finalized and pruned block hashes.

It is guaranteed that all of the `NewBlock` hashes seen prior to this `Finalized` event will either be marked as finalized or pruned, and that no hashes will be left unaccounted for here?

I think that the answer is "yes", because it makes logical sense to me, but would like to confirm this!

(One reason I care is that, in order to keep track of runtime updates, I need to track any new block hashes that contain them, and then when I see a finalized event I can check if any of the finalized block hashes are blocks with a runtime event in them. If I know that all new blocks are either finalized or pruned, I can just clear out any block hashes I'm tracking, rather than clear the specific hashes that are mentioned as finalized or pruned. Another reason that I care is that I am buffering block events from the latest finalized block hash, and again it's easier here to just clear out all events in my buffer each time I see a new finalized event)

**Comment by tomaka** [comment]
The answer is yes

Being able to do what you're doing is very precisely why it's been designed the way it is.

**Comment by jsdw** [comment]
Thankyou @tomaka for the clarification!
